name: Spell Check

on:
  push:
    branches: [main]
  pull_request:

jobs:
  spellcheck:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install cSpell
        run: npm install -g cspell

      - name: Run cSpell
        run: cspell "**/*.{ex,exs,md,yml,yaml}" --config .cspell.yaml
